GET http://localhost:8080/users

###
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "ankit",
    "age": 33,
    "id":3
}

###
GET  http://localhost:8080/users/2

###
GET  http://localhost:8080/users/3